### PR TITLE
Remove Pager from SD Wear

### PR DESCRIPTION
**Pull request by finger563**
* pager reverts to simple scrollview
* remove auto-fit-text views for chart titles
* allow settings menu title to float (toggle-able when it is tapped)

This PR has not been confirmed to have desired UI changes from the BU and the BRs - it is just for tech testing right now.

### CODE REVIEW

**Comment by finger563** [comment]
latest commits have removed the ability to float the settings menu title - since no one i talked to seemed to think it was a meaningful feature (and I didn't really like it...)

**Comment by finger563** [comment]
I've gotten the official `meh` of approval from Ben, so we're good to merge if you two review and approve

**Comment by finger563** [comment]
this closes #489

**Comment by bradmartin** [comment]
Only thing I see, is if that one instance of `autofit-text` being gone removes all usage from the app, we should remove the dependency if it's not needed anymore from the app to reduce bringing it into the APKs.

**Pull request merged**
