### PR TITLE
Sensor updates to support other WearOS watches

### PR DESCRIPTION
**Pull request by finger563**
To support watches (such as the Pro 3 and upcoming E3) which do not expose the virtual `LINEAR_ACCELERATION` sensor, we can compute the gravity and acceleration from the raw accelerometer data. This change occurs in both the PT.W and SD.W apps.

Additionally, updates to the hardware / software on the devices necessitate the use of an updated sensor API when registering for updates from the `LOW_LATENCY_OFFBODY_DETECT` sensor - which is used by SD.W for detecting if it is on / off the user's wrist. This updated API requires that we additionally provide a boolean indicating whether or not the sensor in question is a wake-up sensor (which the offbody-detect sensor is).

Finally, some watches support multi-function buttons - additional hardware buttons which are programmable by the user and which apps can respond to. We will leverage this button to act as a hardware button that can turn power assist off without leaving the app - which happens if you press the power button.

* use the `TYPE_ACCELEROMETER` sensor instead of the `TYPE_LINEAR_ACCELERATION`
* filter the linear acceleration & gravity vectors out of the raw accelerometer data following the [android developer documentation](https://developer.android.com/guide/topics/sensors/sensors_motion#sensors-motion-accel)
* update the nativescript-android-sensors library and associated SensorService wrapper to include the optional `isWakeUpSensor` parameter when registering for sensor updates
* Add key handler for the multi-function button so that it turns power assist off without leaving the app
* Roll back animated circle plugin for better compatibility across devices

### CODE REVIEW

**Comment by finger563** [comment]
related #829 - this PR replaces that PR since it was easier to make a new PR and continue development off the main branch than to merge and fix conflicts there.

**Comment by finger563** [comment]
@bradmartin  one thing that is odd - **on both the Pro 3 and the E3**, the call to `this.androidSensorClass.startSensor( TYPE_LOW_LATENCY_OFFBODY_DETECT, delay, max_reporting_delay )` is returning `null` indicating that the underlying call to [sensorManager.registerListener(...)](https://developer.android.com/reference/android/hardware/SensorManager#registerListener(android.hardware.SensorEventListener,%20android.hardware.Sensor,%20int)) is returning `false` indicating that it cannot start the sensor.  This is odd given that both of those devices do have an `off body detect` sensor (type 34).

**Comment by bradmartin** [comment]
Android version on the 3? Maybe it's a new permission handling situation we have to work with.

**Comment by finger563** [comment]
Hmmm yea I thought about that, but the docs don't say any permissions are required as far as I can tell

**Comment by finger563** [comment]
According to the devs at Mobvoi - we should be passing `true` as the second argument to [`getDefaultSensor(...)`](https://developer.android.com/reference/android/hardware/SensorManager#getDefaultSensor(int,%20boolean)) which would probably work - i'll try it on the e3 in the office later this week.

**Comment by finger563** [comment]
Dependent on:
* https://github.com/bradmartin/XSensor/issues/3
* https://github.com/bradmartin/nativescript-android-sensors/issues/2

**Comment by finger563** [comment]
@bradmartin I have confirmed that the updated code which sets the `isWakeUpSensor = true` for the `LOW_LATENCY_OFFBODY_DETECT` sensor does properly enable the sensor on the E3 and the Pro 3 👍

**Review by p-ranav — APPROVED** [review]

**Pull request merged**
