### PR TITLE
Closes #762

### LINKED ISSUE #762: Chore: Update apps to NS 6.4

### PR DESCRIPTION
**Pull request by bradmartin**
Mainly wanted to get this in for testing on WearOS apps, some runtime changes which might help some of our crashes.

### CODE REVIEW

**Comment by bradmartin** [comment]
No actual app logic changes in this. Purely updating our core-modules fork to be latest off `6.4.1` NS. Some formatting and some import changes because of an error running the PT.M app without AOT was throwing odd issues, so `timeout` changes made to some files with actually doing the import for the timer module and using it directly. Turned out to be an AOT issue with `main.ts` imports which ns-angular not being imported high up enough in the imports. So no real change to app functionality.

**Comment by finger563** [comment]
I don't quite follow - why is ns-angular used at all for the wear apps?

**Comment by bradmartin** [comment]
It wasn't for the wear, that was about PT.M sorry for not being specific on that part.

**Comment by finger563** [comment]
ah no it's my fault - i see you said PT.M now, just wasn't reading closely enough :P

**Pull request merged**
